nav:
  - title: Les Héroïnes
    items:
      - title: Chelinka
        path: heroines/chelinka
      - title: Someul
        path: heroines/someul
      - title: Neptune
        path: heroines/neptune

  - title: Épisodes
    items:
      - title: Saison 1
        path: saisons/saison-1
      - title: Saison 2
        path: saisons/saison-2
      - title: Saison 3
        path: saisons/saison-3
      - title: Saison 4
        path: saisons/saison-4
      - title: Pilotes
        path: episodes/pilotes
      - title: Hors-séries
        path: episodes/hors-series

  - title: L'Univers
    items:
      - title: Personnages
        path: personnages
      - title: Lieux
        path: lieux
      - title: Guildes
        path: guildes
      - title: Magie
        path: magie
      - title: Bestiaire
        path: bestiaire
